Apps/cart/urls.py
from django.urls import path
from .views import CartDetailPageView, SuccessView

app_name = 'cart'
urlpatterns = [
    path("", CartDetailPageView, name='cart'),
    path("success", SuccessView, name='success'),
]

Apps/core/urls.py
from django.urls import path
from . import views


app_name = "core"
urlpatterns = [
    path('', views.FrontPageView, name='frontpage'),
    path('contact', views.ContactPageView, name='contact'),
    path('about', views.AboutPageView, name='about'),
]

Apps/store/urls.py
from django.urls import path
from .views import ProductDetailView, CategoryDetailView, SearchProductsView


app_name = 'store'
urlpatterns = [
    path("products/<slug:slug>/", ProductDetailView, name="product_detail"),
    path("categories/<slug:slug>/", CategoryDetailView, name="category_detail"),
    path("search/", SearchProductsView, name="search"),
]

Apps/userprofile/urls.py
from django.urls import path
from .views import MyAccountView

app_name = 'myaccount'
urlpatterns = [
	path('', MyAccountView, name='myaccount'),
]

e_commerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView, LoginView

from userprofile.views import SignUpView

import core.urls
import store.urls
import cart.urls
import api.urls
import userprofile.urls

urlpatterns = [
    path('', include(core.urls)),
    path('cart/', include(cart.urls)),
    path('api/', include(api.urls)),
    path('store/', include(store.urls)),
    path('myaccount/', include(userprofile.urls)),
    path('admin/', admin.site.urls),
    path('signup/', SignUpView, name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Apps/core/models.py
from django.db import models

# Create your models here.

Apps/core/views.py
from django.shortcuts import render
from store.models import Product

def FrontPageView(request):
    products = Product.objects.filter(is_featured=True)

    context = {
        "products": products
    }

    return render(request, 'frontpage.html', context=context)

def ContactPageView(request):
    return render(request, 'contact.html')


def AboutPageView(request):
    return render(request, 'about.html')

Apps/core/templates/about.html
{% extends "base.html" %}

{% block title %}About | {% endblock %}

{% block content %}
<h1 class="text-lg m-4">This is the information about E-commerce website</h1>
{% endblock content %}

Apps/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}{% endblock %}E-commerce</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/primeicons/3.0.0/primeicons.css" integrity="sha512-Rxb6R6A7p1fiHvhjB7B417xsqg/D7eummpTlNpIVo2qgLbHNlMwdi1Ig180Ddp0ssWSJI/8Z8AHcWWlqw+cS9A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="stylesheet" href="{% static 'main.css' %}">
        
        <script src="https://cdn.tailwindcss.com"></script>
        <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
        <script src="https://unpkg.com/vuex@4.1.0/dist/vuex.global.js"></script>
<body>

    <nav class="flex flex-col md:flex-row items-center justify-between flex-wrap md:bg-black" id='navbarapp' data-cartlength="{{ cart.get_total_length }}" data-totalprice="{{ cart.get_total_price }}">
        <div class="w-full md:w-min text-nowrap flex items-center justify-between bg-black  p-6">
            <a href="{% url 'core:frontpage' %}" class="text-2xl text-white">E-Commerce</a>
            
            <div>
                <form method="get" action="{% url 'store:search' %}">
                    <input class="border rounded-md ml-4 mr-2 h-8 p-2" type="text" name="query" placeholder="Search..." value="{{ query }}" required>
                    <button type="submit" class="text-white text-xl"><i class="pi pi-search"></i></button>
                </form>
            </div>

            <a @click="toggleMenu()" role="button" id="burger" class="text-white text-xl sm:inline md:hidden">
                <i class="pi pi-bars"></i>
            </a>
        </div>

        <div class="flex flex-row items-center justify-center text-black md:bg-black md:text-white m-0">
            <div id = "main-navbar" class="flex flex-col items-center justify-center gap-4 md:flex md:flex-row" :class="{'hidden': menuClass}">
                {% for category in menu_categories %}
                    <div>
                       <a class="text-lg transition-all duration-200 hover:text-xl" href="{% url 'store:category_detail' category.slug %}">{{ category.title }}</a>
                    </div>
                {% endfor %}
                <div>
                    <a class="text-lg transition-all duration-200 hover:text-xl" href="{% url 'core:contact' %}">Contact</a>
                </div>
                <div>
                    <a class="text-3xl transition-all duration-200 hover:text-4xl" href="{% url 'cart:cart' %}"><i class="pi pi-shopping-cart"></i>([[ numItems ]])</a>
                </div>
                {% if request.user.is_authenticated %}
                    <div class="mr-4">
                        <a class="text-3xl transition-all duration-200 hover:text-4xl" href="{% url 'myaccount:myaccount' %}"><i class="pi pi-user"></i></a>
                    </div>
                {% else %}
                    <div class="mr-4">
                        <a class="text-lg transition-all duration-200 hover:text-xl" href="{% url 'login' %}">Log in</a>
                    </div>
                {% endif %}
                
            </div>
        </div>

    </nav>

    {% block content %}
    {% endblock content %}

    {% include 'parts/newsletter.html' %}

    <footer class="w-full bg-black text-white p-4">
        <div class="flex flex-row items-start justify-between flex-wrap">
            <div class="flex-1 min-w-min">
                E-commerce
            </div>
            <div class="flex-1 min-w-min">
                <a href="{% url 'core:contact' %}" class="block my-2">Contact</a>
                <a href="{% url 'core:about' %}" class="block my-2">About</a>
            </div>
        </div>
    </footer>

    {% comment %} <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script> {% endcomment %}

    <script>
        var store = new Vuex.Store({
            state: {
                numItems: parseInt(document.getElementById("navbarapp").dataset.cartlength),
                totalPrice: parseFloat(document.getElementById("navbarapp").dataset.totalprice) 
            },
            mutations: {
                increment(state, quantity){
                    state.numItems += quantity;
                },
                changeTotalPrice(state, price){
                    state.totalPrice += price;
                }
            }
        })

        var navbarapp = Vue.createApp({
            delimiters: ['[[', ']]'],
            data() {
                return {
                    menuClass: true
                }
            },
            store: store,
            computed: {
                numItems: function() {
                    return store.state.numItems;
                }
            },
            methods: {
                toggleMenu() {
                    this.menuClass = !this.menuClass;
                    console.log(this.menuClass);
                }
            }
        });

        navbarapp.mount("#navbarapp");
    </script>
    {% block script %}
    {% endblock %}
</body>
</html>

Apps/core/templates/contact.html
{% extends "base.html" %}

{% block title %}Contact | {% endblock %}

{% block content %}
<h1>Contact <h1>
{% endblock content %}

Apps/core/templates/frontpage.html
{% extends "base.html" %}

{% block content %}
<div class="flex items-center justify-center p-6 bg-slate-50 flex-wrap">
    {% for product in products %}
        <div class="flex-1 max-w-72 min-w-48 rounded overflow-hidden shadow-xl m-5 bg-slate-200">
            <div class="px-6 py-4">
                <div class="w-full font-bold text-xl mb-2 flex justify-center items-center">
                    <img src="{{ product.thumbnail.url }}">
                </div>
                <div class="font-bold text-xl mb-2">
                    {{ product.title }}
                </div>
                <p class="text-gray-700 text-base">
                    {{ product.price }}$
                </p>
            </div>
            <div class="text-center p-2 border-t-2 border-black/[0.6]">
                <a class="text-sky-600" href="{% url 'store:product_detail' product.slug %}">View</a>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock content %}